"""Change PropertyImage: remove image_data blob, add file_path string

Revision ID: 31c14fb7d4ab
Revises: 4198cfa69d73
Create Date: 2026-02-05 11:08:33.336988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '31c14fb7d4ab'
down_revision = '4198cfa69d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add file_path as nullable first
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
    
    # Step 2: Set default values for existing rows
    conn = op.get_bind()
    conn.execute(text("""
        UPDATE property_images 
        SET file_path = '/uploads/placeholder.jpg' 
        WHERE file_path IS NULL
    """))
    
    # Step 3: Now change file_path to NOT NULL
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               nullable=False)
    
    # Step 4: Remove the image_data column
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.drop_column('image_data')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add back image_data as nullable first
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.BLOB(), nullable=True))
    
    # Step 2: Remove file_path column
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.drop_column('file_path')