"""Add host_id to properties

Revision ID: 50e0dbbc2271
Revises: 866e30a1aee7
Create Date: 2026-01-22 18:16:58.898917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e0dbbc2271'
down_revision = '866e30a1aee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_properties_host_id_users', 'users', ['host_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_properties_host_id_users', type_='foreignkey')

    # ### end Alembic commands ###
