"""Add idempotency_key and error_log to Payment model

Revision ID: add_payment_error_handling
Revises: d1199f205b9a
Create Date: 2026-03-10 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_payment_error_handling'
down_revision = 'd1199f205b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_log', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_payments_idempotency_key', ['idempotency_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payments_idempotency_key', type_='unique')
        batch_op.drop_column('error_log')
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
