"""Add M-PESA fields to Payment model

Revision ID: d1199f205b9a
Revises: 50e0dbbc2271
Create Date: 2026-01-24 19:23:04.845820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1199f205b9a'
down_revision = '50e0dbbc2271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_response_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mpesa_response_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('mpesa_response_description')
        batch_op.drop_column('mpesa_response_code')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('mpesa_receipt_number')

    # ### end Alembic commands ###
