"""Add PropertyImage table for storing images in database

Revision ID: f20d01bb18e4
Revises: d1199f205b9a
Create Date: 2026-02-04 23:35:07.390662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f20d01bb18e4'
down_revision = 'd1199f205b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
